[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 20

[[main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 30

[[main]]
  identifier = "cv"
  name = "CV"
  url = "/cv/"
  weight = 40
