colorScheme = "slate"
defaultAppearance = "dark"
enableSearch = true
mainSections = ["posts"]

[author]
name = "Coty Sutherland"
image = "img/profile.jpeg"
headline = "People-First Leader | Open Source Advocate | Engineering with Purpose"
bio = "Coty Sutherland is a senior software engineering leader with more than a decade of experience at Red Hat. He contributes to open source, mentors engineering teams, and supports Indigenous-led nonprofits. Coty is now exploring AI, personal growth tools, and practical ways to help others thrive in tech and life."
links = [
  { github = "https://github.com/csutherl" },
  { linkedin = "https://linkedin.com/in/cotysutherland" },
  { twitter = "https://twitter.com/cotysutherland" }
]

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile" # valid options: page, profile, custom
showRecent = true
recentLimit = 5

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = true
editURL = "https://github.com/csutherl/cotysutherland.com/blob/main/content/"
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = true
showWordCount = true
showComments = false
sharingLinks = []

[list]
showBreadcrumbs = true
showSummary = true
showTableOfContents = true
showTaxonomies = false
groupByYear = true
paginationWidth = 1

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
